# Generated by Django 5.1.6 on 2025-03-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_restaurant_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
