# Generated by Django 5.1.6 on 2025-03-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_user_created_at_alter_user_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(default="bandung", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="webiste",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
