# Generated by Django 5.1.6 on 2025-03-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_user_is_active_remove_user_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
