# Generated by Django 5.1.6 on 2025-03-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
