# Generated by Django 5.1.6 on 2025-03-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
