# Generated by Django 5.1.6 on 2025-03-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_user_is_superuser"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="webiste",
            new_name="website",
        ),
    ]
